import Head from "next/head"
import Sidebar from "../components/Sidebar"
import Drawer from "../components/Drawer"

export default function App() {
  return (
    <div className='App'>
      <Head>
        <title>Note App</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
        {/* <link rel='icon' href='/favicon.ico' /> */}
      </Head>
      <Sidebar />
      <Drawer />
    </div>
  )
}
